web:
  build: .
  command: ./start.sh
  ports:
   - "8080:8080"
  volumes:
   - ./:/ws/src/github.com/gophergala2016/ring_leader
  links:
   - rethinkdb
   - redis
rethinkdb:
  image: rethinkdb:2.2.3
  ports:
   - "8081:8080"
  volumes_from:
    - dbData
dbData:
  image: alpine:3.3
  volumes:
    - ./.dbdata:/data
  command: tail -f /dev/null
redisData:
  image: alpine:3.3
  volumes:
    - ./.redisdata:/data
  command: tail -f /dev/null
redis:
  image: redis:3.0.6-alpine
  volumes_from:
    - redisData
